// All user-facing text. Buyer screens: Hinglish by default, Hindi (Devanagari)
// by toggle. Admin screens: Hinglish labels, English on the settings page.

const hinglish = {
  shopName: "RD Fashion",
  tagline: "Wholesale · Karol Bagh, Delhi",
  wholesaleOnly: "Sirf wholesale · Retail nahi · Har design pe minimum piece likhe hain",
  wholesaleRate: "Wholesale rate",
  wholesaleOrder: "Wholesale order",
  since: "Wholesale manufacturer aur trader · 25 saal se",
  optional: "zaroori nahi",
  cityPick: "Apna sheher chunein",
  citySearch: "Sheher dhoondein (Hindi ya English)",
  cityOther: "List mein nahi? Naam likhein",
  cityUse: (c: string) => `"${c}" chunein`,
  cityRequired: "Sheher chunein",
  cityChange: "Badlein",
  callNow: "Call karein",
  cart: "Cart",
  perPiece: "/ piece",
  minTag: (n: number) => `Min ${n} pcs`,
  filterAll: "Sab",
  filterTshirt: "T-shirts",
  filterLower: "Lowers",
  filterCargo: "Cargos",
  filterJacket: "Jackets",
  filterNew: "New",
  noProducts: "Abhi koi design nahi hai. Call karein.",
  soldOut: "Sold out",
  soldOutSize: "Khatam",
  colour: "Colour",
  sizes: "Size aur piece",
  fabric: "Fabric",
  realPhoto: "Asli photo",
  running: (pieces: number, amount: string) => `${pieces} pcs · ${amount}`,
  addToCart: "Cart mein daalein",
  minNeeded: (n: number) => `Kam se kam ${n} piece chahiye`,
  cartEmpty: "Cart khaali hai",
  browse: "Design dekhein",
  addMore: "Aur design dekhein",
  remove: "Hatayein",
  lineShort: (n: number, missing: number) => `Kam se kam ${n} piece chahiye (${missing} aur)`,
  totalPieces: "Total piece",
  totalAmount: "Total",
  sendOrder: "Order bhejein",
  checkoutTitle: "Wholesale order ke liye details",
  name: "Naam",
  shop: "Dukaan ka naam",
  city: "Sheher",
  mobile: "Mobile",
  mobileHint: "10 digit mobile number · isi pe call aayega",
  required: "Zaroori hai",
  mobileInvalid: "10 digit ka sahi mobile number daalein",
  sendOnWhatsapp: "WhatsApp pe order bhejein",
  sending: "Order save ho raha hai…",
  sentTitle: (code: string) => `Order ${code} save ho gaya`,
  sentBody: "WhatsApp khul raha hai. Wahan Send dabayein.",
  openWhatsapp: "WhatsApp kholein",
  notOpening: "WhatsApp nahi khula? Message copy karke 9313877748 pe bhejein ya call karein.",
  copy: "Message copy karein",
  copied: "Copy ho gaya",
  failedTitle: "Order save nahi hua",
  failedBody: "Internet check karein, ya yeh message copy karke WhatsApp karein, ya call karein.",
  retry: "Phir se try karein",
  viewOrder: "Order dekhein",
  orderTitle: (code: string) => `Wholesale order ${code}`,
  orderNotFound: "Yeh order nahi mila",
  status: "Status",
  statuses: {
    new: "Naya",
    contacted: "Baat hui",
    confirmed: "Confirm",
    dispatched: "Dispatch ho gaya",
    cancelled: "Cancel",
  } as Record<string, string>,
  errors: {
    moq: "Har colour mein minimum piece poore karein",
    unavailable: "Ek design ab available nahi hai, cart se hatayein",
    bad_size: "Ek size ab khatam hai, cart check karein",
    rate_limited: "Bahut saare order ek saath. Thodi der baad try karein ya call karein",
    invalid_buyer: "Details check karein",
    generic: "Kuch galat ho gaya",
  } as Record<string, string>,
  back: "Wapas",
  address: "Pata",
  instagram: "Instagram",
  hours: "Timing",
  rating: "Google rating",
  langToggle: "हिंदी",
};

type BuyerStrings = typeof hinglish;

const hindi: BuyerStrings = {
  shopName: "RD Fashion",
  tagline: "होलसेल · करोल बाग, दिल्ली",
  wholesaleOnly: "सिर्फ होलसेल · रिटेल नहीं · हर डिज़ाइन पर कम से कम पीस लिखे हैं",
  wholesaleRate: "होलसेल रेट",
  wholesaleOrder: "होलसेल ऑर्डर",
  since: "होलसेल निर्माता और व्यापारी · 25 साल से",
  optional: "ज़रूरी नहीं",
  cityPick: "अपना शहर चुनें",
  citySearch: "शहर ढूँढें (हिंदी या English)",
  cityOther: "सूची में नहीं? नाम लिखें",
  cityUse: (c) => `"${c}" चुनें`,
  cityRequired: "शहर चुनें",
  cityChange: "बदलें",
  callNow: "कॉल करें",
  cart: "कार्ट",
  perPiece: "/ पीस",
  minTag: (n) => `कम से कम ${n} पीस`,
  filterAll: "सब",
  filterTshirt: "टी-शर्ट",
  filterLower: "लोअर",
  filterCargo: "कार्गो",
  filterJacket: "जैकेट",
  filterNew: "नया",
  noProducts: "अभी कोई डिज़ाइन नहीं है। कॉल करें।",
  soldOut: "खत्म",
  soldOutSize: "खत्म",
  colour: "रंग",
  sizes: "साइज़ और पीस",
  fabric: "कपड़ा",
  realPhoto: "असली फोटो",
  running: (pieces, amount) => `${pieces} पीस · ${amount}`,
  addToCart: "कार्ट में डालें",
  minNeeded: (n) => `कम से कम ${n} पीस चाहिए`,
  cartEmpty: "कार्ट खाली है",
  browse: "डिज़ाइन देखें",
  addMore: "और डिज़ाइन देखें",
  remove: "हटाएँ",
  lineShort: (n, missing) => `कम से कम ${n} पीस चाहिए (${missing} और)`,
  totalPieces: "कुल पीस",
  totalAmount: "कुल",
  sendOrder: "ऑर्डर भेजें",
  checkoutTitle: "होलसेल ऑर्डर के लिए जानकारी",
  name: "नाम",
  shop: "दुकान का नाम",
  city: "शहर",
  mobile: "मोबाइल",
  mobileHint: "10 अंकों का मोबाइल नंबर · इसी पर कॉल आएगा",
  required: "ज़रूरी है",
  mobileInvalid: "10 अंकों का सही मोबाइल नंबर डालें",
  sendOnWhatsapp: "व्हाट्सऐप पर ऑर्डर भेजें",
  sending: "ऑर्डर सेव हो रहा है…",
  sentTitle: (code) => `ऑर्डर ${code} सेव हो गया`,
  sentBody: "व्हाट्सऐप खुल रहा है। वहाँ Send दबाएँ।",
  openWhatsapp: "व्हाट्सऐप खोलें",
  notOpening: "व्हाट्सऐप नहीं खुला? मैसेज कॉपी करके 9313877748 पर भेजें या कॉल करें।",
  copy: "मैसेज कॉपी करें",
  copied: "कॉपी हो गया",
  failedTitle: "ऑर्डर सेव नहीं हुआ",
  failedBody: "इंटरनेट चेक करें, या यह मैसेज कॉपी करके व्हाट्सऐप करें, या कॉल करें।",
  retry: "फिर से कोशिश करें",
  viewOrder: "ऑर्डर देखें",
  orderTitle: (code) => `होलसेल ऑर्डर ${code}`,
  orderNotFound: "यह ऑर्डर नहीं मिला",
  status: "स्थिति",
  statuses: {
    new: "नया",
    contacted: "बात हुई",
    confirmed: "पक्का",
    dispatched: "भेज दिया",
    cancelled: "रद्द",
  },
  errors: {
    moq: "हर रंग में कम से कम पीस पूरे करें",
    unavailable: "एक डिज़ाइन अब उपलब्ध नहीं है, कार्ट से हटाएँ",
    bad_size: "एक साइज़ अब खत्म है, कार्ट चेक करें",
    rate_limited: "बहुत सारे ऑर्डर एक साथ। थोड़ी देर बाद कोशिश करें या कॉल करें",
    invalid_buyer: "जानकारी चेक करें",
    generic: "कुछ गलत हो गया",
  },
  back: "वापस",
  address: "पता",
  instagram: "इंस्टाग्राम",
  hours: "समय",
  rating: "गूगल रेटिंग",
  langToggle: "Hinglish",
};

export type Lang = "hinglish" | "hindi";
export const buyerStrings: Record<Lang, BuyerStrings> = { hinglish, hindi };
export type { BuyerStrings };

export const admin = {
  title: "RD Fashion Admin",
  login: "Admin login",
  phone: "Mobile number",
  sendOtp: "OTP bhejein",
  otp: "OTP",
  verify: "Login karein",
  notAllowed: "Yeh number admin list mein nahi hai",
  otpSent: (phone: string) => `OTP ${phone} pe bheja gaya`,
  logout: "Logout",
  nav: { orders: "Orders", upload: "Upload (WhatsApp)", products: "Designs", new: "Naya design (manual)", stats: "Stats", settings: "Settings" },
  inbox: "Orders",
  unread: (n: number) => `${n} naye`,
  all: "Sab",
  noOrders: "Koi order nahi",
  call: "Call",
  whatsapp: "WhatsApp",
  status: "Status",
  statuses: {
    new: "New",
    contacted: "Contacted",
    confirmed: "Confirmed",
    dispatched: "Dispatched",
    cancelled: "Cancelled",
  } as Record<string, string>,
  finalAmount: "Final amount (₹)",
  advanceAmount: "Advance (₹)",
  note: "Note (e.g. final rate 240)",
  transport: "Transport",
  lr: "LR number",
  cancelReason: "Cancel reason",
  cancelReasons: ["no reply", "price", "out of stock", "other"],
  save: "Save karein",
  saved: "Save ho gaya",
  buyer: "Buyer",
  items: "Items",
  source: "Source",
  catalogueTotal: "Catalogue total",
  enableNotifications: "Naye order ki notification on karein",
  notificationsOn: "Notification on hai",
  notificationsBlocked: "Browser ne notification block ki hai",
  // Publish flow
  newDesign: "Naya design",
  step: (n: number, total: number) => `Step ${n}/${total}`,
  pickPhoto: "Photo lein ya gallery se chunein",
  analysing: "Photo dekh rahe hain…",
  designName: "Design ka naam",
  category: "Category",
  categories: { tshirt: "T-shirt", lower: "Lower", cargo: "Cargo", jacket: "Jacket" } as Record<string, string>,
  printType: "Print",
  printTypes: { solid: "Plain", print: "Print", stripe: "Stripe" } as Record<string, string>,
  printWarning: "Print design: har colour ki asli photo daalein, recolour theek nahi aata",
  pickColours: "Colours chunein",
  customColour: "Aur colour (naam)",
  add: "Add",
  colourPhoto: "Is colour ki photo (optional)",
  price: "Price per piece (₹)",
  moq: "Min pieces per colour",
  fabric: "Fabric",
  gsm: "GSM",
  sizeSet: "Sizes",
  generate: "Model photo banayein",
  saveWithoutAi: "Asli photo se banayein (AI nahi)",
  approve: "Approve",
  retry: "Retry",
  useOriginal: "Asli photo use karein",
  approved: "Approved",
  generating: "Ban raha hai…",
  failed: "Nahi bana",
  queued: "Line mein",
  publish: "Publish karein",
  publishBlocked: "Pehle sab colours approve karein",
  published: "Design live hai",
  shareLink: "Product link",
  shareCaption: "Reel caption",
  copy: "Copy",
  // Products
  products: "Designs",
  live: "Live",
  hidden: "Hidden",
  draft: "Draft",
  soldOut: "Sold out",
  hide: "Hide",
  show: "Live karein",
  markSoldOut: "Sold out",
  up: "Upar",
  down: "Neeche",
  edit: "Edit",
  sizeSoldOut: "Sold out sizes (tap)",
  colourSoldOut: "Colour sold out",
  // Stats
  stats: "Stats",
  last7: "7 din",
  last30: "30 din",
  visitsBySource: "Visits by source",
  topByViews: "Top designs by views",
  topByPieces: "Top designs by pieces ordered",
  funnel: "Funnel",
  ordersByCity: "Orders by city",
  // Settings (English)
  settings: "Settings",
  shopDetails: "Shop details",
  palette: "Colour palette",
  sizeSets: "Size sets per category",
  whatsappNumber: "WhatsApp number (orders land here)",
  adminPhones: "Admin phone numbers",
  ownerOnly: "Only the owner number can change these",
  baseModels: "Base model (one model for every AI image)",
  popularCities: "City buttons at checkout (comma separated, in order)",
  uploadLink: "Papa's upload link (no login needed; keep it private)",
  uploadLinkOff: "Upload link is off: set UPLOAD_TOKEN (16+ characters) in Vercel.",
  integrations: "Automation status",
};

// Papa's upload link (/u/<token>/ and /admin/upload). Hinglish, big and short.
export const uploader = {
  title: "Naya maal upload",
  subtitle: "Wholesale catalogue · RD Fashion",
  how: [
    "WhatsApp ya gallery se photos chunein (ek design ke saare colour ek saath bhej sakte hain)",
    "Rate likhein agar sab ka ek hi hai",
    "Upload dabayein: design aur colour apne aap ban jayenge",
  ],
  pick: "Photos chunein",
  picked: (n: number) => `${n} photo chuni`,
  rateAll: "Sab ka wholesale rate (₹ per piece, zaroori nahi)",
  upload: "Upload karein",
  uploading: (done: number, total: number) => `Upload ho raha hai… ${done}/${total}`,
  sorting: "Design aur colour bana rahe hain… (1 minute tak)",
  doneSummary: (designs: number, colours: number) => `${designs} design, ${colours} colour bane`,
  aiQueued: "AI model photo ban rahi hai (sab mein ek hi model). Yeh page khula rakhein ya baad mein aayein.",
  aiMissing: "AI photo ke liye FAL_KEY set karna hai. Tab tak asli photo lagi hai.",
  groupedSimple: "Claude set nahi hai, isliye har photo alag design bani. Naam badal kar publish karein.",
  shareHint: "Tip: Chrome menu → 'Add to Home screen'. Phir WhatsApp mein photo → Share → RD Upload.",
  review: "Publish ke liye taiyaar",
  nothing: "Abhi kuch baaki nahi. Upar se naye photos daalein.",
  live: "Live",
  draft: "Draft",
  name: "Design ka naam",
  category: "Category",
  rate: "Wholesale rate (₹ / piece)",
  moq: "Minimum piece (har colour)",
  sizes: "Size (tap karke chunein)",
  publish: "Publish karein",
  published: "Live ho gaya",
  colours: "Colour",
  okPhoto: "Theek hai",
  useShop: "Asli photo",
  retryAi: "Dobara AI",
  makeAi: "AI model photo banayein",
  remove: "Hatayein",
  deleteDraft: "Design hatayein",
  generating: "AI photo ban rahi hai…",
  waitingApproval: "AI photo dekh kar 'Theek hai' dabayein",
  failed: "AI photo nahi bani",
  batches: "Pichhle upload",
  batchStatus: { collecting: "Photos aa rahi hain", processing: "Ban raha hai", ready: "Ho gaya", failed: "Nahi hua" } as Record<string, string>,
  fromWhatsapp: "WhatsApp se",
  fromLink: "Link se",
  error: "Kuch galat ho gaya",
};
